// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PastPapers.ContentApi.Data;

#nullable disable

namespace PastPapers.ContentApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PastPapers.ContentApi.Features.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ExamSeason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exam_season");

                    b.Property<short>("ExamYear")
                        .HasColumnType("smallint")
                        .HasColumnName("exam_year");

                    b.Property<string>("MemoImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memo_image_url");

                    b.Property<short>("PaperNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("paper_number");

                    b.Property<string>("QuestionImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_image_url");

                    b.Property<string>("QuestionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TopicId", "ExamYear", "ExamSeason", "PaperNumber", "DisplayOrder", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("questions", "content", t =>
                        {
                            t.HasCheckConstraint("ck_questions_exam_year", "exam_year BETWEEN 1996 AND 2100");

                            t.HasCheckConstraint("ck_questions_paper_number", "paper_number BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("subjects", "content");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8475ca5-e465-4c16-a445-e9f043054976"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Mathematics",
                            Slug = "mathematics"
                        },
                        new
                        {
                            Id = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Physical Sciences",
                            Slug = "physical-sciences"
                        });
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Topics.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Grade", "Slug")
                        .IsUnique();

                    b.ToTable("topics", "content", t =>
                        {
                            t.HasCheckConstraint("ck_topics_grade", "grade BETWEEN 10 AND 12");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fe0d037-2212-4134-8dd5-59000f040d90"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            Grade = (short)12,
                            Name = "Algebra, Equations, and Inequalities",
                            Slug = "algebra-equations-and-inequalities",
                            SubjectId = new Guid("d8475ca5-e465-4c16-a445-e9f043054976")
                        },
                        new
                        {
                            Id = new Guid("50461d4e-9824-4d5c-ae08-3fcaa46bfd9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            Grade = (short)12,
                            Name = "Newtonian Mechanics",
                            Slug = "newtonian-mechanics",
                            SubjectId = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc")
                        },
                        new
                        {
                            Id = new Guid("62bbbf58-791b-40dd-8bb4-1294a04a5897"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 2,
                            Grade = (short)12,
                            Name = "Doppler Effect",
                            Slug = "doppler-effect",
                            SubjectId = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc")
                        },
                        new
                        {
                            Id = new Guid("2a9eaed1-51a4-47d1-958a-c87982cdcf4d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 3,
                            Grade = (short)12,
                            Name = "Electricity and Magnetism",
                            Slug = "electricity-and-magnetism",
                            SubjectId = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc")
                        },
                        new
                        {
                            Id = new Guid("6472c568-1ac8-447d-8526-66196e7a164b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 4,
                            Grade = (short)12,
                            Name = "Electrodynamics",
                            Slug = "electrodynamics",
                            SubjectId = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc")
                        },
                        new
                        {
                            Id = new Guid("70022de8-3747-4a58-a872-378cf299b9e1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 5,
                            Grade = (short)12,
                            Name = "Optical Phenomena",
                            Slug = "optical-phenomena",
                            SubjectId = new Guid("4d8aa865-32d6-41fa-a1cf-f9a09fdcd7cc")
                        });
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Questions.Question", b =>
                {
                    b.HasOne("PastPapers.ContentApi.Features.Topics.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Topics.Topic", b =>
                {
                    b.HasOne("PastPapers.ContentApi.Features.Subjects.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Subjects.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("PastPapers.ContentApi.Features.Topics.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
